version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
#      - checkout
#      - run: mkdir test-results

      - run: mvn clean test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/testng/results/
      - store_artifacts:
          path: ~/testng/results/
