version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mkdir test-results

      - run: mvn clean test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./target/surefire-reports/testng-results.xml" -exec cp {} ~/test-results/testng/testng-results.xml \;
          when: always
      - store_test_results:
          path: target/surefire-reports/testng-results.xml
      - store_artifacts:
          path: ~/testng/results/
      - store_artifacts:
          path:  testng/results/
