version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mkdir test-results
#      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./target/surefire-reports/.*xml" -exec cp {} ~/test-results/testng/ \;
          when: always
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: ~/testng/results/
      - store_artifacts:
          path:  testng/results/
